const ActionTypes = {
    // LOGIN
    LOGIN_REQ: "LOGIN_REQ",
    LOGIN_OK: "LOGIN_OK",
    LOGIN_ERR: "LOGIN_ERR",

    // LOGOUT
    LOGOUT_REQ: "LOGOUT_REQ",
    LOGOUT_OK: "LOGOUT_OK",
    LOGOUT_ERR: "LOGOUT_ERR",

    // INTERVENTIONS
    GET_ALL_INTERVENTIONS_REQ: "GET_ALL_INTERVENTIONS_REQ",
    GET_ALL_INTERVENTIONS_OK:"GET_ALL_INTERVENTIONS_OK",
    GET_ALL_INTERVENTIONS_ERR:"GET_ALL_INTERVENTIONS_ERR",
};

export default ActionTypes;