const ActionTypes = {
    // LOGIN
    LOGIN_REQ: "LOGIN_REQ",
    LOGIN_OK: "LOGIN_OK",
    LOGIN_ERR: "LOGIN_ERR",

    // LOGOUT
    LOGOUT_REQ: "LOGOUT_REQ",
    LOGOUT_OK: "LOGOUT_OK",
    LOGOUT_ERR: "LOGOUT_ERR",

    // INTERVENTIONS
    GET_ALL_INTERVENTIONS_REQ: "GET_ALL_INTERVENTIONS_REQ",
    GET_ALL_INTERVENTIONS_OK:"GET_ALL_INTERVENTIONS_OK",
    GET_ALL_INTERVENTIONS_ERR:"GET_ALL_INTERVENTIONS_ERR",

    GET_INTERVENTION_BY_ID_REQ: "GET_INTERVENTION_BY_ID_REQ",
    GET_INTERVENTION_BY_ID_OK:"GET_INTERVENTION_BY_ID_OK",
    GET_INTERVENTION_BY_ID_ERR:"GET_INTERVENTION_BY_ID_ERR",

    SET_CURRENT_INTERVENTION: "SET_CURRENT_INTERVENTION",
    RESET_CURRENT_INTERVENTION: "RESET_CURRENT_INTERVENTION",

    CREATE_INTERVENTION_REQ: "CREATE_INTERVENTION_REQ",
    CREATE_INTERVENTION_OK: "CREATE_INTERVENTION_OK",
    CREATE_INTERVENTION_ERR: "CREATE_INTERVENTION_ERR",

    UPDATE_INTERVENTION_REQ: "UPDATE_INTERVENTION_REQ",
    UPDATE_INTERVENTION_OK: "UPDATE_INTERVENTION_OK",
    UPDATE_INTERVENTION_ERR: "UPDATE_INTERVENTION_ERR",

    DELETE_INTERVENTION_REQ: "DELETE_INTERVENTION_REQ",
    DELETE_INTERVENTION_OK: "DELETE_INTERVENTION_OK",
    DELETE_INTERVENTION_ERR: "DELETE_INTERVENTION_ERR",

    // CUSTOMERS
    GET_ALL_CUSTOMERS_REQ: "GET_ALL_CUSTOMERS_REQ",
    GET_ALL_CUSTOMERS_OK:"GET_ALL_CUSTOMERS_OK",
    GET_ALL_CUSTOMERS_ERR:"GET_ALL_CUSTOMERS_ERR",

    GET_CUSTOMER_BY_ID_REQ: "GET_CUSTOMER_BY_ID_REQ",
    GET_CUSTOMER_BY_ID_OK:"GET_CUSTOMER_BY_ID_OK",
    GET_CUSTOMER_BY_ID_ERR:"GET_CUSTOMER_BY_ID_ERR",

    SET_CURRENT_CUSTOMER: "SET_CURRENT_CUSTOMER",
    RESET_CURRENT_CUSTOMER: "RESET_CURRENT_CUSTOMER",

    CREATE_CUSTOMER_REQ: "CREATE_CUSTOMER_REQ",
    CREATE_CUSTOMER_OK: "CREATE_CUSTOMER_OK",
    CREATE_CUSTOMER_ERR: "CREATE_CUSTOMER_ERR",

    UPDATE_CUSTOMER_REQ: "UPDATE_CUSTOMER_REQ",
    UPDATE_CUSTOMER_OK: "UPDATE_CUSTOMER_OK",
    UPDATE_CUSTOMER_ERR: "UPDATE_CUSTOMER_ERR",

    DELETE_CUSTOMER_REQ: "DELETE_CUSTOMER_REQ",
    DELETE_CUSTOMER_OK: "DELETE_CUSTOMER_OK",
    DELETE_CUSTOMER_ERR: "DELETE_CUSTOMER_ERR",

    // EMPLOYEES
    GET_ALL_EMPLOYEES_REQ: "GET_ALL_EMPLOYEES_REQ",
    GET_ALL_EMPLOYEES_OK:"GET_ALL_EMPLOYEES_OK",
    GET_ALL_EMPLOYEES_ERR:"GET_ALL_EMPLOYEES_ERR",

    GET_EMPLOYEE_BY_ID_REQ: "GET_EMPLOYEE_BY_ID_REQ",
    GET_EMPLOYEE_BY_ID_OK:"GET_EMPLOYEE_BY_ID_OK",
    GET_EMPLOYEE_BY_ID_ERR:"GET_EMPLOYEE_BY_ID_ERR",

    SET_CURRENT_EMPLOYEE: "SET_CURRENT_EMPLOYEE",
    RESET_CURRENT_EMPLOYEE: "RESET_CURRENT_EMPLOYEE",

    CREATE_EMPLOYEE_REQ: "CREATE_EMPLOYEE_REQ",
    CREATE_EMPLOYEE_OK: "CREATE_EMPLOYEE_OK",
    CREATE_EMPLOYEE_ERR: "CREATE_EMPLOYEE_ERR",

    UPDATE_EMPLOYEE_REQ: "UPDATE_EMPLOYEE_REQ",
    UPDATE_EMPLOYEE_OK: "UPDATE_EMPLOYEE_OK",
    UPDATE_EMPLOYEE_ERR: "UPDATE_EMPLOYEE_ERR",

    DELETE_EMPLOYEE_REQ: "DELETE_EMPLOYEE_REQ",
    DELETE_EMPLOYEE_OK: "DELETE_EMPLOYEE_OK",
    DELETE_EMPLOYEE_ERR: "DELETE_EMPLOYEE_ERR",
};

export default ActionTypes;